language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - pyrus install -p pyrus.net/Pyrus_Developer-alpha
  - pyrus install PEAR2_Autoload-alpha
script: pyrus run-phpt -r tests || (find . -name *.out | xargs -t cat && exit 1)
